// src/components/affirmations.js
const affirm= [
  "I can do all things through Christ. — Philippians 4:13",
  "The Lord is my shepherd; I shall not want. — Psalm 23:1",
  "For I know the plans I have for you. — Jeremiah 29:11",
  "God is within her, she will not fall. — Psalm 46:5",
  "The joy of the Lord is my strength. — Nehemiah 8:10",
  "Commit to the Lord whatever you do, and your plans will succeed. — Proverbs 16:3",
  "The Lord is my light and my salvation. — Psalm 27:1",
  "I am fearfully and wonderfully made. — Psalm 139:14",
  "Be strong and courageous. — Joshua 1:9",
  "Cast all your anxiety on Him because He cares for you. — 1 Peter 5:7",
  "Trust in the Lord with all your heart. — Proverbs 3:5",
  "The Lord will fight for you; you need only to be still. — Exodus 14:14",
  "God’s grace is sufficient for me. — 2 Corinthians 12:9",
  "Do not be afraid, for I am with you. — Isaiah 41:10",
  "Let the peace of Christ rule in your hearts. — Colossians 3:15",
  "Rejoice in hope, be patient in tribulation, be constant in prayer. — Romans 12:12",
  "Blessed is the one who trusts in the Lord. — Psalm 34:8",
  "I am God’s workmanship, created in Christ Jesus for good works. — Ephesians 2:10",
  "Delight yourself in the Lord, and He will give you the desires of your heart. — Psalm 37:4",
  "The Lord is good, a refuge in times of trouble. — Nahum 1:7",
  "Peace I leave with you; my peace I give you. — John 14:27",
  "God will supply all my needs according to His riches. — Philippians 4:19",
  "The steadfast love of the Lord never ceases. — Lamentations 3:22",
  "Be strong in the Lord and in His mighty power. — Ephesians 6:10",
  "I will fear no evil, for You are with me. — Psalm 23:4",
  "He heals the brokenhearted and binds up their wounds. — Psalm 147:3",
  "I am more than a conqueror through Christ. — Romans 8:37",
  "God’s word is a lamp to my feet and a light to my path. — Psalm 119:105",
  "I am rooted and established in love. — Ephesians 3:17",
  "Cast your burden on the Lord, and He will sustain you. — Psalm 55:22",
  "I am redeemed and forgiven. — Colossians 1:14",
  "Do not be anxious about anything. — Philippians 4:6",
  "My help comes from the Lord, the maker of heaven and earth. — Psalm 121:2",
  "I am blessed coming in and going out. — Deuteronomy 28:6",
  "God is my refuge and strength, an ever-present help. — Psalm 46:1",
  "I am the head and not the tail. — Deuteronomy 28:13",
  "I am the light of the world. — Matthew 5:14",
  "God works all things together for my good. — Romans 8:28",
  "I have the mind of Christ. — 1 Corinthians 2:16",
  "I am chosen, holy, and dearly loved. — Colossians 3:12",
  "The Lord satisfies the desires of my heart. — Psalm 37:4",
];

export default affirm;
